//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seguimiento5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WattsALoan1Entities : DbContext
    {
        public WattsALoan1Entities()
            : base("name=WattsALoan1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SpecifyCurrentBalance(Nullable<System.DateTime> pmtDate, string emplNbr, Nullable<int> laID, Nullable<decimal> pmtAmt)
        {
            var pmtDateParameter = pmtDate.HasValue ?
                new ObjectParameter("PmtDate", pmtDate) :
                new ObjectParameter("PmtDate", typeof(System.DateTime));
    
            var emplNbrParameter = emplNbr != null ?
                new ObjectParameter("EmplNbr", emplNbr) :
                new ObjectParameter("EmplNbr", typeof(string));
    
            var laIDParameter = laID.HasValue ?
                new ObjectParameter("LaID", laID) :
                new ObjectParameter("LaID", typeof(int));
    
            var pmtAmtParameter = pmtAmt.HasValue ?
                new ObjectParameter("PmtAmt", pmtAmt) :
                new ObjectParameter("PmtAmt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpecifyCurrentBalance", pmtDateParameter, emplNbrParameter, laIDParameter, pmtAmtParameter);
        }
    
        public virtual ObjectResult<ShowInformation_Result> ShowInformation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowInformation_Result>("ShowInformation");
        }
    }
}
